export const clientData = [
  {
    id: 1,
    name: "Joshua Damilare",
    email: "c.obilor@gmail.com",
    loan_officer: "Usman Yakubu",
    currency: "₦",
    price: "97,326.08",
    status: "in progress",
    created_at: "November 28, 2015",
  },
  {
    id: 2,
    name: "Ekaete Clement",
    email: "mo.yusuf@gmail.com",
    loan_officer: "Chinedu Ejike",
    currency: "₦",
    price: "30,359.02",
    status: "approved",
    created_at: "May 6, 2012",
  },
  {
    id: 3,
    name: "Ikenna Paul",
    email: "usman.yak@mail.com",
    loan_officer: "Victor James",
    currency: "₦",
    price: "34,694.145",
    status: "approved",
    created_at: "February 28, 2018",
  },
  {
    id: 4,
    name: "ThankGod Iniobong",
    email: "farouk987@gmail.com",
    loan_officer: "Mohammed Yusuf",
    currency: "₦",
    price: "66,000.21",
    status: "approved",
    created_at: "October 31, 2017",
  },
  {
    id: 5,
    name: "Sandra Eze",
    email: "mo.yusuf@gmail.com",
    loan_officer: "Kelechi Nwosu",
    currency: "₦",
    price: "74,349.39",
    status: "approved",
    created_at: "April 28, 2016",
  },
  {
    id: 6,
    name: "Faruq Aminu",
    email: "c.obilor@gmail.com",
    loan_officer: "Adunoluwa Adeyemi",
    currency: "₦",
    price: "901.32",
    status: "rejected",
    created_at: "May 31, 2015",
  },
  {
    id: 7,
    name: "Goodluck Jonathan",
    email: "usman.yak@mail.com",
    loan_officer: "Chineye Obaseki",
    currency: "₦",
    price: "39,542.00",
    status: "in progress",
    created_at: "December 29, 2012",
  },
  {
    id: 8,
    name: "Solomon Effiong",
    email: "daniels_kunle78@hotmail.com",
    loan_officer: "Tope Orodeji",
    currency: "₦",
    price: "96,739.04",
    status: "approved",
    created_at: "February 29, 2012",
  },
  {
    id: 9,
    name: "Solomon Effiong",
    email: "daniels_kunle78@hotmail.com",
    loan_officer: "Tope Orodeji",
    currency: "₦",
    price: "96,739.04",
    status: "approved",
    created_at: "February 29, 2012",
  },
  {
    id: 10,
    name: "Osazie Collins",
    email: "rennyoni@yahoo.com",
    loan_officer: "Vivian Aguoma",
    currency: "₦",
    price: "972,231.00",
    status: "approved",
    created_at: "May 29, 2017",
  },
  {
    id: 11,
    name: "Johnson Mbong",
    email: "mo.yusuf@gmail.com",
    loan_officer: "Oluchi Uzo",
    currency: "₦",
    price: "66,326.09",
    status: "rejected",
    created_at: "February 11, 2014",
  },
];
